### ISSUE TITLE
FastSerial.h

### ISSUE THREAD

**Issue by theailer** [Heliobteixeira/minoposd#2]
Hi!
I can't compile the code because it's asking for FastSerial.h, and I have the file in the same directory as the other files.

I was just trying to change the rssi input to read from the minimosd itself rather than on the ppm stream since I use a rangelink long range system which have a dedicated rssi pin on the receiver.

**Comment by Heliobteixeira** [comment]
That's a library. It should be located in Arduino/libraries/ folder in the respective folder "FastSerial"

**Comment by theailer** [comment]
I moved all the libraries from this repository over to the arduino/libraries directory but now I get this;
avr-gcc: error: unrecognized command line option ‘-assembler-with-cpp’

**Comment by Heliobteixeira** [comment]
Can you confirm you have the latest Arduino 1.6.5 IDE?

**Comment by theailer** [comment]
That I didn't have, used the repository in debian and 1.05 was the latest there, downloading 165 now.
But looking through your files it seems to me that the osd should already take the rssi form the minim and not the cc3d.
This is what im thinking of:
//#define RSSI_PIN          1           // A1 is pin 24
#define RSSI_PIN      3     // ADC3 is pin 26

**Comment by theailer** [comment]
Or is it these lines I should change ?
void analog_rssi_read(void)
{
    if (rssiraw_on) {
        //osd_rssi = analogRead(RSSI_PIN) / 4;              // Just raw value, 0-255. We use this range to better align
        osd_rssi = (uint8_t)(float)((osd_chan7_raw - 992) \* .31135f); //In this example it has to be channel 6, not the PPM slot that EzUHF is using (11), but the number of the Function configured in the GCS input tab, not counting the disabled functions.

```
                                    // with the original code.
} else {
```

#ifdef JR_SPECIALS
// SEARCH GLITCH
        osd_rssi = analogRead(RSSI_PIN)       / 4;          // 1:1 input
#else
        //osd_rssi = analogRead(RSSI_PIN) \* .2  / 4 + osd_rssi \* .8;    // Smooth input
    osd_rssi = (uint8_t)(float)(((osd_chan7_raw - 992) \* .31135f) \* .2 + osd_rssi \* .8);
#endif

**Comment by theailer** [comment]
Now it compiles

**Comment by Heliobteixeira** [comment]
Using:
osd_rssi = (uint8_t)(float)((osd_chan7_raw - 992) \* .31135f);
will get the RSSI value from slot counting 7 from Input Tab

And:
osd_rssi = analogRead(RSSI_PIN) / 4
will get the rssi directly from the respective Pin on the KVOSD

**Comment by Heliobteixeira** [comment]
Also I've not managed to get it working (reading the output from dedicated Rssi pin) with my Frsky X8R.
Somehow it seems there's some RC filter which I can't understand. I'm working on another branch for that (rssipwm_issue)

**Comment by theailer** [comment]
Im gonna report back and see what I find, maybe the result will be different on my receiver ?
But now somehow the board won't let me update the firmware on it, neither via arduino nor minoposd config util. It worked 5 minutes ago =)

**Comment by theailer** [comment]
Now for some unknown reason it was able to flash.
Only thing I did was comment out your osd_rssi = (uin8...
and remove the comments on osd_rssi=analogread...
But now the osd is in a boot loop =)

**Comment by Heliobteixeira** [comment]
Try compile and flash the original code in this repo. Make that change and retry. Flash using config_tool.

**Comment by theailer** [comment]
I'll try that soon.
What are the difference between all the charset ? Is there some documentation on them somewhere?

**Comment by Heliobteixeira** [comment]
From what I've seen the bitmap is diferent also the disposition of chars is diferent so it may show wrong chars

Envoyé de mon iPhone

**Comment by theailer** [comment]
Okey. I erased the eeprom and flashed the exact same file again and now it works. Rssi displays as it should ! 
But I can't get the heading to work on the osd though, it shouldn't require GPS or?

**Comment by Heliobteixeira** [comment]
The CC3D doesn't have a compass so that isn't enabled. The reading you get
in GCS are not accurate.

On Thu, Aug 6, 2015 at 12:52 PM, theailer notifications@github.com wrote:

> Okey. I erased the eeprom and flashed the exact same file again and now it
> works. Rssi displays as it should !
> But I can't get the heading to work on the osd though, it shouldn't
> require GPS or?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Heliobteixeira/minoposd/issues/2#issuecomment-128341689
> .

## 

Tlm: +351 91 665 51 67

email: helio.b.teixeira@gmail.com
          helio.teixeira@jadeportugal.org
          hteixeira@junifeup.pt

**Comment by theailer** [comment]
Ah I should have known that. Thanks for everything
